### ISSUE TITLE
thewire-Adding a new post

### ISSUE THREAD

**Issue by blacktooth** [blacktooth/elgg-ajaxify#5]

**Comment by ewinslow** [comment]
A few todos still:
- You should throw up an ajax loader as soon as the request is submitted to let the user know something is happening.
- In addition to resetting the form fields when the request completes successfully, you should reset the # of characters remaining.
- entities/getentity seems like a useful view, but it is being used to fetch the newest wire post from the system, not necessarily the one that was just created by the user who submitted the form.  Send back the new guid in thewire/add as we discussed and then use that GUID to render the appropriate view.
- Try to modularize things as I describe in the commit comments so that the stream that needs to update and the form that's used to submit the new post are agnostic of each other.

**Comment by ewinslow** [comment]
This wasn't working on experimental last I checked. Did I do something wrong?

**Comment by blacktooth** [comment]
It needs some fixes on the core to work properly. I changed the thewire/reply to use input/plaintext view for rendering the textarea and turned few ids into classes.

**Comment by ewinslow** [comment]
So we should reopen, since it's not working

**Comment by blacktooth** [comment]
The followings modifications on the core will make it work, 
https://github.com/blacktooth/Elgg/commit/56ae895e179c8726c7e999d06c570593291af0da
https://github.com/blacktooth/Elgg/commit/57f1a350cd150533bd6581df7f8f33f9be446de6
